### ISSUE TITLE
Cleanup Layout file and move components to block

### ISSUE THREAD

**Issue by liwoo** [liwoo/cell-connect#1]
- So they will be under `app/components/blocks/layout/sidebar`
- also move the `header` into the `layout` block
- SideNav should reflect the Icons and Menu Items of the previous version of the App
- SideNav active link should work (read more on [Remix](https://remix.run/docs/en/main/hooks/use-location))
- Change the Logo to the correct Logo
- Profile Dropdown data should be extract into an object (`app/components/blocks/layout/profile-dropdown`)

**Comment by glenmiracle18** [comment]
- [✅ ] So they will be under app/components/blocks/layout/sidebar
- [ ✅ ] also move the header into the layout block / _also broke down some elements and put them in the `blocks` folder._
- [ ✅ ] SideNav should reflect the Icons and Menu Items of the previous version of the App
- [✅ ] SideNav active link should work (read more on [Remix](https://remix.run/docs/en/main/hooks/use-location))
- [ ✅ ] Change the Logo to the correct Logo
- [ ✅] Profile Dropdown data should be extract into an object (app/components/blocks/layout/profile-dropdown) **was previously named `UserCombobox`**
