### ISSUE TITLE
Fix Sidebar Minimal Collapsibles

### ISSUE THREAD

**Issue by liwoo** [liwoo/cell-connect#11]
When the Sidebar is minimized, the Collapsible Items must either

1. Change into Popovers which appear on the side when clicked
2. Remove the arrows in the collapsible

![Screenshot 2024-06-17 at 11 07 27 PM](https://github.com/liwoo/famcon/assets/11289074/75e326b2-a3c2-492e-ac8b-854568cb0881)

Also fix the active state of the collapsed child items.

![Screenshot 2024-06-17 at 11 07 08 PM](https://github.com/liwoo/famcon/assets/11289074/8431e96d-2081-4758-ad79-b99fc27e820a)

**Comment by glenmiracle18** [comment]
on it sir

**Comment by glenmiracle18** [comment]
done with this issue
ready for review

![image](https://github.com/liwoo/famcon/assets/89632911/e8d324e5-18f6-4ce8-9be0-9f396e390fd8)

![image](https://github.com/liwoo/famcon/assets/89632911/063f2cd8-9ff8-4ee6-ad1a-f1eb8da6e46b)
