### ISSUE TITLE
Fix Profile Popup when Minimized

### ISSUE THREAD

**Issue by liwoo** [liwoo/cell-connect#12]
Fix user profile popup when sidebar minimized, by hiding the text and just leaving the icons

![Screenshot 2024-06-17 at 11 08 46 PM](https://github.com/liwoo/famcon/assets/11289074/11a6acaf-6cfe-4ff1-bacb-9bdffeb84e7d)

**Comment by glenmiracle18** [comment]
working on it sir

**Comment by glenmiracle18** [comment]
done with this issue.
ready for reviews

![image](https://github.com/liwoo/famcon/assets/89632911/3204a3db-b975-4ed8-b611-258239b7196e)
