### ISSUE TITLE
Fix werid hover color in dark mode

### ISSUE THREAD

**Issue by liwoo** [liwoo/cell-connect#16]
![Screenshot 2024-10-17 at 10 01 25 PM](https://github.com/user-attachments/assets/f30006c6-cad0-4360-a0bd-fd99d47525a8)

**Comment by glenmiracle18** [comment]
done! awaiting review:

![image](https://github.com/user-attachments/assets/f920f8a9-0f98-475a-8c24-d5e47a60632c)
