### ISSUE TITLE
Persist in Local Storage Menu Collapsed State

### ISSUE THREAD

**Issue by liwoo** [liwoo/cell-connect#17]
Right now, when we collapse the menu, and we navigate to another page, it shows the menu uncollapsed. We need to fix this so that when menu is collapsed it should store the state in localstorage.

**Comment by glenmiracle18** [comment]
resolved and ready for review
![image](https://github.com/user-attachments/assets/cb00276f-8368-4598-b1c9-805dadee2de5)

![image](https://github.com/user-attachments/assets/110302e9-64e0-4fe6-8247-5e30b7ea069f)

![Screenshot 2024-10-18 at 5 28 30 PM](https://github.com/user-attachments/assets/4733c1ee-6235-4ff8-81b7-3bf5f1a5df9a)
