### ISSUE TITLE
Fix the Dashboard (home page)

### ISSUE THREAD

**Issue by liwoo** [liwoo/cell-connect#2]
- The table is Broken
- The data from the table should be abstracted outside
- The button on the table is broken
- The data in the right panel should be extracted

**Comment by glenmiracle18** [comment]
- [ ✅] The table is Broken
- [🏁 ] The data from the table should be abstracted outside _still pending..._
- [✅ ] The button on the table is broken
- [ ✅] The data in the right panel should be extracted

![image](https://github.com/liwoo/famcon/assets/89632911/96b7f31e-f2cd-41b4-877c-932d05caaf97)
