### ISSUE TITLE
Fix the UI for showing User Details

### ISSUE THREAD

**Issue by liwoo** [liwoo/cell-connect#3]
![Screenshot 2024-06-03 at 11 35 46 PM](https://github.com/liwoo/famcon/assets/11289074/18789ef4-2964-4411-839d-f29db30f493d)

**Comment by glenmiracle18** [comment]
done and dusted

![image](https://github.com/liwoo/famcon/assets/89632911/3c5178dc-919a-446f-91b4-80a125cb7183)
