### ISSUE TITLE
Create Contributor Charts

### ISSUE THREAD

**Issue by liwoo** [liwoo/cell-connect#6]
[] Total Contributors Card
[] Card for Contributor By Gender
[] Average Contributors
[] Average Dependents

Take inspiration from the cards on the dashboard and then add some [charts](https://www.figma.com/community/file/1136245680428075391/charts-ios-swiftui) like in the Figma.

**Comment by glenmiracle18** [comment]
found [this](https://ant-design-charts.antgroup.com/en/examples/statistics/gauge/#gauge-color) chart that might be simillar to the one on the design.
Lemme know your thoughts

**Comment by glenmiracle18** [comment]
added the sections as required.
waiting for feedback

**Comment by glenmiracle18** [comment]
done with this issue. Just need you fix the copyy
